include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - prefer_const_constructors_in_immutables
